#ifndef SCT_LIB_MACROS_H
#define SCT_LIB_MACROS_H

/*
 * placeholder - macros are generated by cmake from
 * macros.hh.in file when cmake is invoked, and placed
 * in the build tree
 */

#endif  // SCT_LIB_MACROS_H
