// sct/core/macros.hh

#ifndef SCT_CORE_MACROS_HH
#define SCT_CORE_MACROS_HH

/*
 * placeholder - macros are generated by cmake from
 * macros.hh.in file when cmake is invoked, and placed
 * in the build tree
 */

#endif // SCT_CORE_MACROS_HH
